name: Python Code Quality Check

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install flake8 autopep8 isort bandit

    - name: Auto-format code with autopep8
      run: autopep8 --in-place --recursive .

    - name: Sort imports with isort
      run: isort .

    - name: Lint code with flake8
      run: flake8 .

    - name: Run bandit security check
      run: bandit -r .

    - name: Report findings
      run: |
        echo "Linting, formatting, and security checks completed."
