name: Python Code Quality Check

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint and Auto-Format Python Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install flake8 autopep8 isort bandit

    - name: Identify changed files
      id: changed-files
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep ".*\.py$" || true)
        echo "::set-output name=files::$CHANGED_FILES"

    - name: Auto-format changed code with autopep8
      run: |
        for file in ${{ steps.changed-files.outputs.files }}; do
          autopep8 --aggressive --in-place "$file"
        done

    - name: Sort imports with isort
      run: isort .

    - name: Lint changed code with flake8
      run: |
        for file in ${{ steps.changed-files.outputs.files }}; do
          flake8 --select=F "$file"
        done

    - name: Run bandit security check
      run: bandit -r .

    - name: Report findings
      run: |
        echo "Linting, formatting, and security checks completed."
